### PR TITLE
Sprint documents

### PR DESCRIPTION
**Pull request by ClintonCao**
I've added Sprint Backlog 7 and Sprint Retrospective 6.

Please check it again and merge.

### CODE REVIEW

**Comment by boninggong** [comment]
Rule No.1: Never lose money. Rule No.2: Never forget rule

**Comment by boninggong** [comment]
“ Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live. ” - Rick Osborne

I think that this quote is relevant to this pull request. At least for the documents that you pushed in this PR. Btw the ADD is not relevant in this PR.

**Comment by TimBuckers** [comment]
I think you used an outdated branch.

**Comment by ClintonCao** [comment]
Indeed I did, thanks!

**Pull request closed without merging**
