### PR TITLE
Sprint Backlog 4 and Sprint Retrospective 3

### PR DESCRIPTION
**Pull request by ClintonCao**
I've added the sprint documents. Please lemme know if there is something missing.

(I cannot get rid of the green color and I don't know who fill the cell with green ಠ_ಠ )

### CODE REVIEW

**Comment by SunweiWang** [comment]
It looks good, just as we discussed during the meeting, green? Doesn't it look nice?

**Comment by ClintonCao** [comment]
I didn't know if it was on purpose or not.

**Comment by SunweiWang** [comment]
Nope, element of surprise there, :P

**Comment by SunweiWang** [comment]
Since you guys don't like the green, no taste of art.... I had to remove it. :disappointed:

**Comment by Michieldoesburg** [comment]
I liked the green tbh, adds some colour to a world so drab elseways.

**Comment by TimBuckers** [comment]
"There is no reason not to follow your heart" - Steve job
Ziet er goed uit zoals besproken dus ik merge

**Pull request merged**
