### PR TITLE
Source code

### PR DESCRIPTION
**Pull request by Michieldoesburg**
Implemented source code functionality. ProjectInfoFinder has a new method called retrieveCodeFiles which, for every classPath retrieves the code from that class and stores it as a CodeFile object in the field  codeFiles. These are then written as JSON format to a javascript file called CodeFiles.js (src/main/resources), where it is stored as a variable.

All code is documented and tested :dancer:

### CODE REVIEW

**Comment by boninggong** [comment]
🐓 Good job Michiel! I took a quick look and saw that everything is nicely documented. Lets merge this branch before the deadline 🐫

**Comment by ClintonCao** [comment]
Looks good to me. Nice to see that the source code can now be exported. This is needed for CodeMirror.

Though can you fix the warnings? It went from 9 CheckStyle to 21 CheckStyle warnings?

**Comment by Michieldoesburg** [comment]
Decreased to 8 checkstyle warnings now :)

**Comment by ClintonCao** [comment]
Nice fix for the warnings! I will merge this now.

**Pull request merged**
