### PR TITLE
Visualization

### PR DESCRIPTION
**Pull request by boninggong**
Fix of #49 + lots of new features added

### CODE REVIEW

**Comment by ClintonCao** [comment]
Looks good to me. Nice to see that the toggle buttons are working and that you can open the source code (though this is still a example code).  I think that the graphBuilder.js can be removed permanently, as the clients was to keep it to one single visualization.

Looks good to me, nice job!

**Comment by TimBuckers** [comment]
In my opinion it can be merged, but I wrote a big part of the code. So can someone else also review this?

**Comment by SunweiWang** [comment]
ehh, I cannot seem to find this branch on Git
image

**Comment by ClintonCao** [comment]
A temporary branch is made, try that one and see if you still get the same problem.

**Comment by SunweiWang** [comment]
In the branch Visualizer, I can now see the work, it looks good, there are some minor bugs, but it has been planned for next sprint, I think we can merge it. Good jobs! :+1:

**Comment by ClintonCao** [comment]
I will merge this then!

**Pull request merged**
