### PR TITLE
Visualizer upgraded with new features

### PR DESCRIPTION
**Pull request by boninggong**
Lots of new features added. Also processed the feedback from our clients to make the visualization more clear.

### CODE REVIEW

**Comment by SunweiWang** [comment]
Nice work, I like that my suggestion is taken into consideration that we only have one toggle button for relative color setting now. The interface looks much more cleaner. The client's suggestion above 45 degrees ASAT box is implemented, although not completely 45 degrees. I think visualization team has done good jobs.

**Comment by boninggong** [comment]
Thank you for your feedback Sunwei! 
Yeah we know that the angle is not always 45 degrees, it depends on the ratio of the height and the width for now. We will focus on this problem in the next sprint, so it's not yet included in this pull request ;)

**Comment by ClintonCao** [comment]
Besides the irritating bug that is still in the visualizer, seems good to me. Nice that the unused files are removed. The repo is not filled with unused file anymore.

**Comment by boninggong** [comment]
Yup we will fix that in the next sprint too! And the statistics are more accurate now with those unused libraries removed :)

**Comment by TimBuckers** [comment]
Some people don't like change, but you need to embrace change if the alternative is disaster.

**Comment by boninggong** [comment]
"It is not the strongest or the most intelligent who will survive but those who can best manage change." --Charles Darwin

**Pull request merged**
