### PR TITLE
Visualization

### PR DESCRIPTION
**Pull request by TimBuckers**
The visualization of the output json. The treemap and the graph. With filter options for SAT types.

### CODE REVIEW

**Comment by boninggong** [comment]
Goodmorning mr Buckers,

Hereby my review for your pull request as requested. I approve your coding style and I love the clear documentation. Furthermore I don't have too much to add because I wrote a big part of the code too. Your functions go without saying, the naming is clear. 

Gr,

mr Gong

**Comment by ClintonCao** [comment]
I did noticed the random files that you guys have committed, thanks for removing them. Comments are written for the code, which is also nice.  There is one slight problem: The visualization does not work on Mozilla Firefox?

The rest looks good to me.

**Comment by TimBuckers** [comment]
I'm delighted to hear from you, Boning. Thx for the comment Gong.

**Comment by boninggong** [comment]
Thank you for your feedback mr. Cao! We will let our Visualization team look into this and you will hear from us shortly.

**Comment by boninggong** [comment]
ಠ_ಠ

**Comment by TimBuckers** [comment]
Coaa could you test it again?

**Comment by TimBuckers** [comment]
Now also the checkboxes behave properly

**Comment by boninggong** [comment]
Here you go mr. Cao, we were glad to assist you. If there are any more problems with your browser please don't hesitate to tell us.

**Comment by ClintonCao** [comment]
It seems to work fine now, nice job!

**Comment by Michieldoesburg** [comment]
Finally time to merge this beast, well done!

**Pull request merged**
