### PR TITLE
Asat settings functionality

### PR DESCRIPTION
**Pull request by Michieldoesburg**
FindBugs is implemented and runs. Findbugs, PMD and CheckStyle now read and use settings files.

### CODE REVIEW

**Comment by ClintonCao** [comment]
Looks good to me but by turning the settings class into a singleton class, will it influence the ability for the user to select the configuration file?

And last but not least, can you fix the warnings :stuck_out_tongue:

**Comment by Michieldoesburg** [comment]
It won't influence the ability to select the configuration file because this file can still be changed at any time. I will fix the warnings.

**Comment by ClintonCao** [comment]
Oh, I skipped through the getters and settters of the class. Then it shouldn't influence the ability to select the file.

**Comment by ClintonCao** [comment]
Also I assume that the test will be written in a different PR?

**Comment by Michieldoesburg** [comment]
Yes the tests will be written in a different PR.

**Comment by ClintonCao** [comment]
I've fixed some of the warnings.

**Comment by boninggong** [comment]
The code looks good to me Michiel! I also saw that Clinton fixed some warnings which is nice. This PR is ready to merge if the build will pass!

**Comment by SunweiWang** [comment]
Yes, the checkstyle warnings are fixed

**Pull request merged**
