### PR TITLE
Visualizer fix of filters

### PR DESCRIPTION
**Pull request by boninggong**
The filters on ASATs and categories when displaying ASAT or categories are bug free now.
They also work in combination with the relative button.

### CODE REVIEW

**Comment by ClintonCao** [comment]
Nice to see that the filters are working! Nice job fixing it! :+1: . Though I did find another bug.

I did the following:
- Started the `main.html`.
- Clicked on `ASAT` radio button.
- Clicked twice on `default`.
- Turned off `Doc. Conventions` in `Maintainability Defects`
- Go back one higher level: The colors and bars are not slanted in `Brain` for `Team.java`
-  Click on `Brain` and go back. The slanted bars are back.

**Comment by boninggong** [comment]
Oke, thanks for the bug report. I will look into this and try to fix it

**Comment by boninggong** [comment]
@ClintonCao Yoo Cao, it is fixed. Could you review it again please?

**Comment by ClintonCao** [comment]
Nice it is indeed fixed now, nice job! 

Last thing: Can you remove the link in the title? :stuck_out_tongue:

**Comment by boninggong** [comment]
Gvd

**Comment by SunweiWang** [comment]
The new filter looks pretty good, Good job, Boning!
:+1:

**Pull request merged**
