### PR TITLE
Source code visualizer

### PR DESCRIPTION
**Pull request by boninggong**
Update the visualizer with multiple new features and bug fixes:
- From the deepest level you can show the source code 
- In the source code warnings will be highlighted according to the type of ASAT
- On hover it will show what the warnings says and in which category it belongs
- The current path is showed above the treemap
- On hover over a package/class in the treemap shows the info in a seperated div

Features to add for later:
- Filter on warnings in the source code visualizer

### CODE REVIEW

**Comment by ClintonCao** [comment]
Looks nice! Nice that you guys have implemented some of the feedback that was given from the Interaction Design feedback.

Is it true that the code highlighting does not completely work? It seems that only CheckStyle is highlighted.

**Comment by SunweiWang** [comment]
It looks good, and you guys have implemented features from the feedback given by our clients during the meeting on Wednesday, the clickable path is pretty cool! :+1:

**Comment by boninggong** [comment]
Thanks for your feedback @ClintonCao and @SunweiWang ! 
We will try to implement the filter within the source code visualizer now. If that one works we can review the whole PR and merge it if there are no problems.

**Comment by ClintonCao** [comment]
The filtering seems to work fine. I think we can merge this then. Anyone else have something to say?

**Comment by Michieldoesburg** [comment]
Nope, we can merge this!

**Pull request merged**
