### PR TITLE
Requirements updated with feedback from Moritz

### PR DESCRIPTION
**Pull request by boninggong**

### CODE REVIEW

**Comment by ClintonCao** [comment]
You added the wrong point from the should have in the must have xD

**Comment by boninggong** [comment]
Oh I see, thank you for your review!

**Comment by boninggong** [comment]
I've fixed it according to the feedback of Clinton. Please review again :)

**Comment by SunweiWang** [comment]
doesn't Clinton mean that the last point in the must have need to be moved to should have? Or did I understood wrong?

**Comment by boninggong** [comment]
Euhm, what do you mean exactly?

**Comment by SunweiWang** [comment]
Oh, nvm, just saw your whatsapp message, it is Moritz who suggested to put the point with General Defect Classification in the must have category. The rest looks good to me.

**Comment by boninggong** [comment]
Oke :)

**Comment by ClintonCao** [comment]
Looks good, I'll merge this PR.

**Pull request merged**
