### PR TITLE
tooltip as detail panel issue #115

### PR DESCRIPTION
**Pull request by TimBuckers**
Is this a good solution? 

Problem: when there is a long message the detail panel is harder to read.

### CODE REVIEW

**Comment by boninggong** [comment]
It's a good solution to the inconsistency that was mentioned in issue 115. 👍 

The only thing is that long messages are not being displayed properly. We need a small tweak to also show multiple warnings.

**Comment by ClintonCao** [comment]
It is indeed consistent with the previous solution for the packages/classes. I do agree with Boning, longer messages do become more troublesome (or even when there are more than 3 for a line).

**Comment by TimBuckers** [comment]
so does anyone has a good proposition?

**Comment by ClintonCao** [comment]
I thought that maybe we can make it clickable, but I am not sure whether that really solves the problem. And also I am not sure whether it is clear for the user (as in interaction).

**Comment by boninggong** [comment]
Maybe a scrolling option, where you will scroll through the message when you are pointing on a warning and use your scroll button. If that's possible and not too hard to implement of course.

**Pull request closed without merging**
