### PR TITLE
Refactored the code based on the feedback of SIG and also from our TA.

### PR DESCRIPTION
**Pull request by ClintonCao**
I've refactored the code of the system based on the feedback of SIG and also from our TA.

I did the following things:
- In `GUI.java`, I have removed the single use variables. This shortens the `start` method.
- In `GUIController.java`, I have made two nested classes inside `GUIController`. These two classes are are the event handler classes for the buttons of the GUI. There are no more anonymous classes anymore within `GUIController`.
- In `Summarizer.java`, the methods of equals and hashcode are removed. This are implemented in the subclasses.
- I have merged the updated Parsers.
- I have moved the jar of `Lombok` to the `lib` folder.
- I have updated the `pom.xml`. We don't use Cobertura anymore, but rather JaCoCo. This is because Cobertura does not support Java 1.8 and causes exceptions to be thrown in the build log. (In my opinion, this is not very clean).
- I have excluded `Main.java`, `GUIController.java`, `GUI.java` and `SelectButtonEventHandler.java` from the reports of JaCoCo. This is because we are not going to test the GUI using automated tests (as it might be hard to do to and `Main` is just the driver of the system).

Please review and let me know if there are any questions.

### CODE REVIEW

**Comment by ClintonCao** [comment]
So apparently the build is failing (though it passed before I made the PR) for some odd reason? I am currently investigating why it is failing..

**Comment by ClintonCao** [comment]
The problem is now fixed, though I still do not understand the reason why the build failed. Before I made the PR everything worked fine, but after making the PR the list of summarizers in `testGroupByComponents` had a different order.  I couldn't find the cause for it. 

Also I added toString methods for all the summarizer and warning classes. I think that this might be helpful when a test fails.

**Comment by SunweiWang** [comment]
I refactored the code of all Parsers based on the feedback of SIG. It made our code more clear, and prevent the code duplication.

**Comment by ClintonCao** [comment]
I've added a markdown file, where you can write about the coverage and decisions that were made for testing.

**Comment by boninggong** [comment]
Wow, lots of changes! I had a quick look at the code and overall it looked good. Good job for processing the feedback from SIG 👍

**Pull request merged**
