### PR TITLE
Analyzer

### PR DESCRIPTION
**Pull request by Michieldoesburg**
Cobertura runs but for some reason produces all zero output. Checkstyle and PMD run correctly now and produce their output.

### CODE REVIEW

**Comment by ClintonCao** [comment]
Code is written in a way that is quite easy to understand, nice job!

Though I do have some comments:

- Why not move the `commands` attribute from the subclasses (of `CommandBuilder`) to their superclass? All subclasses have this same attribute and the type of the attribute is the same. I don't see why you shouldn't put it in `CommandBuilder`.

- Why are some classes documented and some are not (fully) documented? I get that writing JavaDoc for getters and setters is not that important, but do write JavaDoc for the other methods.

-  Because of what I said in the previous point, there are 43 CheckStyle warnings now...there was 11 warnings after merging last pull request. (Warning for JavaDoc for getters and setters are turned off by the way.)

- Though the whole team did not come to an agreement on how the structure of the packages should be, can you organize the components that you wrote in packages?

-  Last but not least, where are the tests for the components? From all the component that you've wrote, the component that is very hard to test is the Analyser component. It is very hard to test the `analyse` method.

Besides the points mentioned above, the code looks good to me. If there are any questions, don't hesitate to ask here or on WhatsApp.

**Comment by SunweiWang** [comment]
I agree with Clinton on the case of CommandBuilder class, I think our code can be more concise, so I made some changes to the code, also made a new pull request to analyzer branch, which refactor the command builders. Other than that, I think the code is nicely written, and can be merged after merge my pull request first.

**Comment by Michieldoesburg** [comment]
Sunwei has fixed the inheritance problem in commandbuilder. I have added javadoc to all classes, fixed most relevant checkstyle warnings, and moved the commandbuilders into their own package. The only thing that's really left is writing unit tests.

**Comment by ClintonCao** [comment]
I've added some more JavaDoc to some of the classes and methods. Do realize that subclasses does not inherit JavaDoc of their superclasses. JavaDoc should start with a sentence and also have a description for the tags.

Remember to update this branch with the changes in master! (before or after writing the test).

**Comment by SunweiWang** [comment]
Please do write JUnit tests before Friday, the rest I think it's good to merge.

**Pull request merged**
