### PR TITLE
Added links for documents.

### PR DESCRIPTION
**Pull request by ClintonCao**
Added the links for the documents. Please check that if the links are working before merging.

### CODE REVIEW

**Comment by Michieldoesburg** [comment]
maven execution research link does not work

**Comment by ClintonCao** [comment]
Gimme a minute, thanks!

**Comment by boninggong** [comment]
Yups what Michiel said, other links are fine :+1:

**Comment by ClintonCao** [comment]
It is working on my computer for some reason. Let me use my laptop

**Comment by Michieldoesburg** [comment]
Is it just me or does github lag terribly when displaying pdf files?

**Comment by SunweiWang** [comment]
why maven execution research link works with me?

**Comment by ClintonCao** [comment]
@Michieldoesburg I think it is just you :stuck_out_tongue: . I haven't experience any lag yet..

**Comment by ClintonCao** [comment]
@Michieldoesburg @boninggong Ummmm it also works fine on m laptop, not sure why it is not working for you guys...

**Comment by Michieldoesburg** [comment]
No idea, it just directs to https://github.com/ClintonCao/Contextproject-TSE/blob/master and says 404 page not found

**Comment by ClintonCao** [comment]
It should take you to this link: https://github.com/ClintonCao/Contextproject-TSE/blob/master/documentation/MavenResearch/MavenResearch.md , which is the same one in the markdown document....

**Comment by SunweiWang** [comment]
Yeah, for me it works fine, not sure why is it not working with Michiel. @boninggong  do you have the same problem?

**Comment by Michieldoesburg** [comment]
Works for me now!

**Comment by ClintonCao** [comment]
Nice :+1::

**Pull request merged**
