### PR TITLE
Feedback on Sprint Plan 1

### PR DESCRIPTION
**Pull request by breijm**
Let me know if you have any questions regarding the feedback.

### CODE REVIEW

**Comment by SunweiWang** [comment]
Bastiaan, you mentioned that we should estimate tasks in points instead of hours, we were wondering how exactly do you estimate tasks in points? we have never used points before.

**Comment by breijm** [comment]
@SunweiWang Thanks for the question! I've added a short guide how_to_use_points_in_sprint_planning.md

Let me know if you have any further questions

**Comment by ClintonCao** [comment]
@breijm It is a very nice explanation, we will use it in the next sprint! I don't have any other questions. Does anyone else have a question? If not, I will merge this pull request.

**Comment by TimBuckers** [comment]
It's clear, so we can now merge the pull request

**Pull request merged**
