### PR TITLE
PMD Parser 

### PR DESCRIPTION
**Pull request by SunweiWang**
make the PMD parser can read the new rule set to give correct classification.

### CODE REVIEW

**Comment by SunweiWang** [comment]
Since the output from PMD is different from the previously Maven generated PMD outputs, the rule set of the output is then parse differently,  but I still kept the MavenPMDParser, so if we decide to run Maven, it is still available.

**Comment by ClintonCao** [comment]
I think that this will solve the empty classification for PMD warnings in the JSON file. We first have to see what the answer is from our client before we merge this.

**Comment by boninggong** [comment]
Thank you for solving this! I used the previous output and found out that the PMD warnings did not have any classifications. Quick fix guys :)

**Comment by SunweiWang** [comment]
@ClintonCao , in this PR, I have mavenPMDParser and PMDParser as two files, you can merge it, and we can decide what to keep in the master when we get the feedbacks from the client.

**Comment by ClintonCao** [comment]
@SunweiWang I will have to check whether this reallt solves the problem and if it does, the coverage dropped. So you know what you need to do :stuck_out_tongue:

**Comment by SunweiWang** [comment]
Alright, let's see if it solves the problem, I will write the test cases in an independent branch for this class and some other classes.

**Comment by ClintonCao** [comment]
@SunweiWang I ran the analyser again and it seems to be producing the classifications, you can start with the tests :wink:

**Comment by Michieldoesburg** [comment]
Time to merge this.

**Pull request merged**
