### PR TITLE
Feedback Code Evolution Quality 2

### PR DESCRIPTION
**Pull request by breijm**
Questions, Comments, Feedback - Let me know

### CODE REVIEW

**Comment by boninggong** [comment]
Thank you for your feedback :)

**Comment by ClintonCao** [comment]
Thanks for the feedback @breijm! I do not quite understand point 3 and 6.

The output are written to the folders? Do you mean that we should also commit the outputs of the tools to the repo?

Also I don't quite understand what you mean with making the instances immutable for `groupBy`.

**Comment by ClintonCao** [comment]
My questions are already answered during the meeting.

@breijm I have tried looking online on how I could write the the output of the tools to the repo with Travis, but I couldn't find the right commands. Is it possible to send me a link for the instruction?

**Comment by ClintonCao** [comment]
I think we can merge this pull request. I am currently working on the output of the tools on #31 .

**Pull request merged**
