### PR TITLE
Coveralls and Tools Output.

### PR DESCRIPTION
**Pull request by ClintonCao**
I have configured Travis to use coveralls to show the coverage of our project. 

I still need to configure travis to push the output files of the tools to the repo, so this is PR is not complete.

### CODE REVIEW

**Comment by ClintonCao** [comment]
Lol coveralls writes comments to the PR, didn't know that

**Comment by boninggong** [comment]
What ur doing Coveralls?

**Comment by ClintonCao** [comment]
The pull request is now complete; it is not easy to push the output to the repo via Travis. Now Travis shows the output in the build log at the end.

**Comment by Michieldoesburg** [comment]
Nice work clinton, seeing coverage on travis is great.

**Pull request merged**
