### PR TITLE
Feedback Product Planning Draft

### PR DESCRIPTION
**Pull request by breijm**
Questions, comments, feedback all is welcome.

### CODE REVIEW

**Comment by ClintonCao** [comment]
I think the feedback is pretty clear. We will update the product planning. 

We used epics because in the book, the author also used epics (which he explained as user stories that represents larger body of work). We were confused which method we should use to write the high-level product backlog. 

We will use MoSCoW for the high-level product backlog then. 

I do have one question; If we want to use MoSCoW to write the high-level product backlog (which is the requirement document that we've wrote), I am certain that we are over the maximum amount of pages (6). (Right now we are already close to 6 pages).

Do you have any advice how we can we can add it to the product planning? Should I add an appendix?

**Comment by SunweiWang** [comment]
I have questions regarding, glossary, do you mean by SAT not clear, should we change to ASAT instead? And for DoD for documents, do I have to add that we need to have grammar/spelling changed for product planning, product vision?

**Comment by breijm** [comment]
@ClintonCao 

I've seen the term used as well, feel free to use it if the book does as well.
Adding the MoSCoW as an appendix would be fine, just refer to it in the main text.

**Comment by breijm** [comment]
@SunweiWang The term SAT is fine, it's just that the word _programme_ means something else than the word _program_

For the DoD, it's advised that you add these to make your definition as complete as possible

**Comment by ClintonCao** [comment]
@breijm 

Thanks for the answer, I will add the MoSCoW as an appendix.

**Comment by ClintonCao** [comment]
Merging this pull request.

**Pull request merged**
