### PR TITLE
Se grades sprint 8 and final product

### PR DESCRIPTION
**Pull request by breijm**
Last Grades including Sprint 8 and the Final Product as described in the rubrics.

### CODE REVIEW

**Comment by ClintonCao** [comment]
@breijm Thank you for all the feedback, suggestions, grade and help that you have given throughout this project! Our product wouldn't have been as good as it is now without the feedback, suggestions and help. 

"I think it's very important to have a feedback loop, where you're constantly thinking about what you've done and how you could be doing it better. I think that's the single best piece of advice: constantly think about how you could be doing things better and questioning yourself." - Elon Musk

**Comment by boninggong** [comment]
“We all need people who will give us feedback. That’s how we improve.” – Bill Gates

**Comment by Michieldoesburg** [comment]
Is Clinton hinting @breijm should be questioning himself? This seems pretty aggressive to me...

**Comment by boninggong** [comment]
"The world is so competitive, aggressive, consumive, selfish and during the time we spend here we must be all but that." – Jose Mourinho

**Comment by ClintonCao** [comment]
@Michieldoesburg That is not what I meant......

**Comment by Michieldoesburg** [comment]
@ClintonCao Yeah yeah... you know what, see ya in court buddy 
https://www.google.nl/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwjs05-un7bNAhVlDsAKHbghBFIQjRwIBw&url=http%3A%2F%2Fwestafricannewsinternational.com%2Fagain-court-rules-dasukis-detention-in-order%2F&psig=AFQjCNHNl8VdWxgMm7pU9B1HKfuE9ZN9Rg&ust=1466499722400454

**Comment by breijm** [comment]
@ClintonCao You're welcome, you guys worked hard and deserve to be rewarded for it. Cool quote by Elon.

@boninggong Good quotes to live and work by

@Michieldoesburg I question myself all the time, plus you don't have time for court. Still things to do this week

**Pull request merged**
