### PR TITLE
pointer by color scale radiobuttons and removed some printing

### PR DESCRIPTION
**Pull request by TimBuckers**

### CODE REVIEW

**Comment by boninggong** [comment]
Goodmorning Buckers,

I've found a minor bug in your code. This concerns the Functional Defect Label which is clickable, but when you hover over it, it doesn't show a small hand like the other labels. Could you fix this please?

Other from that the code works!

Yours faithfully,

Boning Gong
BlueTurtle

**Comment by boninggong** [comment]
Oh wauw you fixed it before I commented, you clairvoyant!

**Comment by ClintonCao** [comment]
Seems like the view does indeed change this time :stuck_out_tongue:. Also nice that a different pointer is used now. Nice fix!

**Comment by Michieldoesburg** [comment]
The pointer is a very nice addition, makes it clear what is clickable. Merging this.

**Pull request merged**
