### PR TITLE
General Defect Classification (GDC)

### PR DESCRIPTION
**Pull request by SunweiWang**
Sprint backlog, iteration 3:
user story:
**Categorizing the warnings**: same kinds of warnings should be put into the same category
Using General Defect Classification(GDC), modify the adding classification attributes, change relevent parser, add the categorySummarizer.

### CODE REVIEW

**Comment by ClintonCao** [comment]
I think I've already commented on the branch before the pull request was made. Though I forgot to ask, we don't check whether the `ruleName` is equal anymore in the equals method for the warnings class (CheckStyle, PMD, FindBugs)?

Can you move the attributes of the `PMDWarning` to the top of the constructor?.

And finally can you fix the warnings for the classes that you wrote / fixed? (12 CheckStyle warnings to 52 CheckStyle warnings, yikes....)

**Comment by Michieldoesburg** [comment]
Aside from clinton's points, this looks good.

**Comment by SunweiWang** [comment]
Please merge the #36 , before merge this one.

**Comment by ClintonCao** [comment]
As the warnings fixed and the tests are updated from #41 , we can merge this.

**Pull request merged**
