### PR TITLE
Adapted JSWriter and WarningGrouper based on TA's feedback.

### PR DESCRIPTION
**Pull request by ClintonCao**
I've adapted the JSWriter and the WarningGrouper based on the feedback of our TA. I've removed `@AllArgsConstructor` from WarningGrouper, because it needs to process things in the constructor.

Please review and lemme know if there is something missing.

### CODE REVIEW

**Comment by ClintonCao** [comment]
I've also added some tests for the previous written classes.

**Comment by SunweiWang** [comment]
This PR adapt our code based on TA's feedback for [feedback 2] (https://github.com/ClintonCao/Contextproject-TSE/blob/master/se_feedback/feedback_code_evolution_quality_2.md)

**Comment by ClintonCao** [comment]
I've didn't update `App.java` because most of the code there is to check whether the components works. We should consider whether we want to remove this class or not

**Comment by ClintonCao** [comment]
After discussing with @Michieldoesburg, I've removed the unused field `commands` in `CommandBuilder`. Actually this also makes sure that the wrong command is not made if `builCommand` is accidentally called more than once.

**Comment by Michieldoesburg** [comment]
Looks very nice, I think we can remove App.java. Everyone else agree on this?

**Comment by ClintonCao** [comment]
I completely agree, it is there only to test the components.

**Comment by boninggong** [comment]
Oke sounds good to me, everything still works

**Comment by ClintonCao** [comment]
I've removed `App.java`

**Comment by boninggong** [comment]
Good job

**Pull request merged**
