### PR TITLE
Remove high cyclomatic complexity in Parsers

### PR DESCRIPTION
**Pull request by SunweiWang**
Some code refactor based on TA's feedback from last sprint, remove high cyclomatic complexity in Parsers.

### CODE REVIEW

**Comment by boninggong** [comment]
Good to see that the feedback is processed! Code looks more clear now 👍

**Comment by Michieldoesburg** [comment]
If you only removed the if statements does that mean they were unnecessary to begin with?

**Comment by boninggong** [comment]
I guess so @Michieldoesburg

**Comment by SunweiWang** [comment]
@Michieldoesburg Yes, they were indeed unnecessary, but I guess they were there for the safe check purpose, but in order to reduce cyclomatic complexity as Bastiaan suggested, I will remove them.

**Comment by ClintonCao** [comment]
@SunweiWang I think you've misunderstood wat Bastiaan meant with high complexity. He meant that you can split the whole function into smaller functions. An example of that is in `ProjectInfoFinder`. I am surprised that removing the if statements didn't cause any problems.

**Comment by SunweiWang** [comment]
@ClintonCao "Cyclomatic complexity is a software metric (measurement), used to indicate the complexity of a program. It is a quantitative measure of the number of linearly independent paths through a program's source code. It was developed by Thomas J. McCabe, Sr. in 1976. " (https://en.wikipedia.org/wiki/Cyclomatic_complexity)

**Comment by SunweiWang** [comment]
@ClintonCao in Eclipse, if you run the coverage, then you change from line coverage to complexity, then you will see Parsers are now all 100%, before they were 77%.

**Comment by ClintonCao** [comment]
@SunweiWang yeah I know that, but that is not Bastiaan meant, or else he wouldn't have reference to `ProjectInfoFinder`

**Comment by SunweiWang** [comment]
@ClintonCao  I will ask him on his PR then.

**Comment by ClintonCao** [comment]
image

**Comment by ClintonCao** [comment]
@SunweiWang Have you noticed that if a file has multiple warnings, that you pass the same message to each of the warning? Try running `mvn site` and then check for `JavaControllerTest` It shows the wrong message for line 160.

**Comment by ClintonCao** [comment]
**Update** summation of the warning is right in the analyser, but not in the visualizer!

And by the way, the fix for the message is by doing the following: 
use `warning.getTextContent()` instead of passing the message into the function. Passing it, will change the message for all other PMD warnings in the same class.

**Comment by SunweiWang** [comment]
@ClintonCao  Thanks for spotting the bug, this should be able to fix it, I didn't update the JSON file though, but if you re-run it yourself, the PMD warnings should give the corresponding right messages.

**Comment by Michieldoesburg** [comment]
With Bastiaan's approval this is mergable now

**Pull request merged**
