### PR TITLE
Sprint Backlog 3 and Sprint Retrospective 2

### PR DESCRIPTION
**Pull request by ClintonCao**
I've added the sprint documents. Let me know if there is something missing.

### CODE REVIEW

**Comment by SunweiWang** [comment]
It looks good to me, the only thing is that we don't have any major problem, nor didn't we come up with any improvement, the only thing I can come up is we can have some group motivations.

**Comment by ClintonCao** [comment]
Yeah indeed. But is that really an adjustment?

**Comment by boninggong** [comment]
For me it looks good and you can merge it!

**Comment by SunweiWang** [comment]
This looks good, and is as our team discussed, I think it's ready to merge.

**Pull request merged**
