### PR TITLE
Create executable jar for our project

### PR DESCRIPTION
**Pull request by SunweiWang**
We use Maven shade plugin to create executable jar for our project.

### CODE REVIEW

**Comment by ClintonCao** [comment]
Though a fatJar can be created with Maven, it still needs to be put in the same folder of "ContextProject-TSE". Changing the whole backend might not worth the time for creating the JAR. I guess this is the solution for now.

**Comment by Michieldoesburg** [comment]
Do we want to include the jar on github? I'm not sure I see the point :p.

**Comment by ClintonCao** [comment]
Oh indeed, why were the jars committed?

**Comment by ClintonCao** [comment]
Okay, I have removed the jars! @SunweiWang don't commit everything next time :stuck_out_tongue:

**Comment by Michieldoesburg** [comment]
Alright now it's good to merge :+1:

**Pull request merged**
