### PR TITLE
Added links for final report.

### PR DESCRIPTION
**Pull request by boninggong**

### CODE REVIEW

**Comment by ClintonCao** [comment]
@boninggong what did you do? How can I review my own changes? xD

**Comment by boninggong** [comment]
Idk, should I review my own PR? xD

**Comment by boninggong** [comment]
Your changes are looking good Clinton, lets merge this before the deadline

**Comment by ClintonCao** [comment]
Well there is a mistake in the link. You didn't do your job well, Mr Boning.

**Comment by boninggong** [comment]
Oh must have read over it, sorry for my bad previous review

**Comment by SunweiWang** [comment]
reviewed, I finally understand the link

**Pull request merged**
