### PR TITLE
Background image issue #118

### PR DESCRIPTION
**Pull request by TimBuckers**
Darker background for more contrast.
Opacity background divs increased for readability.

### CODE REVIEW

**Comment by boninggong** [comment]
Good to see that there is some activity again! The darker background is more user friendly and shows a good contrast with the visualization now 👍

**Comment by TimBuckers** [comment]
But I already made the boxes less transparent that was what I meant with: Opacity background divs increased for readability.

I can make de images even darker

**Comment by ClintonCao** [comment]
Well let's see what the others think

**Comment by Michieldoesburg** [comment]
I think it looks good like this. The boxes might be better with a little less transparency, but I think that's more personal taste than readability.

**Comment by ClintonCao** [comment]
I guess this can be merged now?

**Comment by SunweiWang** [comment]
I think the darker background image that Clinton changed will show a clear contrast between the front part and the back. I think it looks good.

**Pull request merged**
