### PR TITLE
Added draft of final report.

### PR DESCRIPTION
**Pull request by ClintonCao**
I've added the draft of the final report. Please review the the draft before merging.

### CODE REVIEW

**Comment by boninggong** [comment]
#100 yay :)

Good job on the report team! I believe this is a good basis for the final report. Next week we can do the finishing touch!

**Comment by SunweiWang** [comment]
My only concern is that we have only two references, but as we discussed, we don't know if we really need references for this final report. So I think it is a well made draft for final report.

**Comment by ClintonCao** [comment]
I guess if more references are needed, we will get some feedback on that?

**Comment by ClintonCao** [comment]
I've added the updated version of the draft.

**Comment by ClintonCao** [comment]
I've made a typo on Moritz's last name. I've fixed it now.

**Comment by SunweiWang** [comment]
Nice fix, we will make sure it is not misspelled in the final report xD

**Pull request merged**
